const BLOCK_SIZE = 16;
const BLOCKS_IN_SMALL_SECTOR = 4;
const BLOCKS_IN_LARGE_SECTOR = 16;
const SMALL_SECTOR_SIZE = BLOCK_SIZE * BLOCKS_IN_SMALL_SECTOR;
const LARGE_SECTOR_SIZE = BLOCK_SIZE * BLOCKS_IN_LARGE_SECTOR;
const PACKET_SIZE = 16;

const MIFARE_1K_TOTAL_SECTORS = 16;
const MIFARE_1K_TOTAL_BLOCKS = BLOCKS_IN_SMALL_SECTOR * MIFARE_1K_TOTAL_SECTORS;
const MIFARE_1K_SECTOR_DATA_SIZE = BLOCK_SIZE * (BLOCKS_IN_SMALL_SECTOR - 1);

const MIFARE_4K_TOTAL_SMALL_SECTORS = 32;
const MIFARE_4K_TOTAL_LARGE_SECTORS = 8;
const MIFARE_4K_SMALL_SECTOR_DATA_SIZE = BLOCK_SIZE * (BLOCKS_IN_SMALL_SECTOR - 1);
const MIFARE_4K_LARGE_SECTOR_DATA_SIZE = BLOCK_SIZE * (BLOCKS_IN_LARGE_SECTOR - 1);
const MIFARE_4K_TOTAL_SECTORS = MIFARE_4K_TOTAL_SMALL_SECTORS + MIFARE_4K_TOTAL_LARGE_SECTORS;
const MIFARE_4K_TOTAL_BLOCKS = BLOCKS_IN_SMALL_SECTOR * MIFARE_4K_TOTAL_SMALL_SECTORS + BLOCKS_IN_LARGE_SECTOR * MIFARE_4K_TOTAL_LARGE_SECTORS;


module.exports = {
    BLOCK_SIZE: BLOCK_SIZE,
    BLOCKS_IN_SMALL_SECTOR: BLOCKS_IN_SMALL_SECTOR,
    BLOCKS_IN_LARGE_SECTOR: BLOCKS_IN_LARGE_SECTOR,

    SMALL_SECTOR_SIZE: SMALL_SECTOR_SIZE,
    LARGE_SECTOR_SIZE: LARGE_SECTOR_SIZE,
    PACKET_SIZE: PACKET_SIZE,

    MIFARE_1K_TOTAL_SECTORS: MIFARE_1K_TOTAL_SECTORS,
    MIFARE_1K_TOTAL_BLOCKS: MIFARE_1K_TOTAL_BLOCKS,
    MIFARE_1K_SECTOR_DATA_SIZE: MIFARE_1K_SECTOR_DATA_SIZE,

    MIFARE_4K_TOTAL_SMALL_SECTORS: MIFARE_4K_TOTAL_SMALL_SECTORS,
    MIFARE_4K_TOTAL_LARGE_SECTORS: MIFARE_4K_TOTAL_LARGE_SECTORS,
    MIFARE_4K_SMALL_SECTOR_DATA_SIZE: MIFARE_4K_SMALL_SECTOR_DATA_SIZE,
    MIFARE_4K_LARGE_SECTOR_DATA_SIZE: MIFARE_4K_LARGE_SECTOR_DATA_SIZE,
    MIFARE_4K_TOTAL_SECTORS: MIFARE_4K_TOTAL_SECTORS,
    MIFARE_4K_TOTAL_BLOCKS: MIFARE_4K_TOTAL_BLOCKS
}